name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: My first step
        uses: ./.github/actions/test.yml
      - name: My second step
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: |
          git branch
