name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Build API
        run: |
          pwd
          ls
          echo "Run script"
          sh ./common.sh
          cd ..
          echo "this is a new line" >> file.txt
          ls
