name: Deploy

on: push
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sh ./common.sh
          date > generated.txt
          git config user.name Andrey
          git config user.email and.isaev.v@yandex.ru
          git add .
          git commit -m "generated"
          git push
